<a href="https://colab.research.google.com/github/varungupta/DLPytorch60m/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

## Tensor Initialization

In [3]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [4]:
np_data = np.array(data)
x_np = torch.from_numpy(np_data)
x_np

tensor([[1, 2],
        [3, 4]])

In [5]:
x_ones = torch.ones_like(x_data)
print(f"Ones: {x_ones}")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Rand: {x_rand}")

Ones: tensor([[1, 1],
        [1, 1]])
Rand: tensor([[0.4871, 0.3091],
        [0.4444, 0.5626]])


In [6]:
shape = (3, 4)

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: {rand_tensor}")
print(f"Ones Tensor: {ones_tensor}")
print(f"Zeros Tensor: {zeros_tensor}")

Random Tensor: tensor([[0.9915, 0.4755, 0.8341, 0.7921],
        [0.2575, 0.1575, 0.2357, 0.6208],
        [0.6856, 0.2459, 0.3344, 0.6557]])
Ones Tensor: tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
Zeros Tensor: tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


## Tensor Attributes

In [7]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device of tensor: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device of tensor: cpu


In [8]:
device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else 'cpu'
tensor = tensor.to(device)
print(f"Device of tensor: {tensor.device}")

Device of tensor: cuda:0


## Tensor Operations

In [13]:
t = torch.ones(4, 4)
t[2, :] = 0
t

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.]])

In [15]:
t1s = torch.ones(4, 4)
trs = torch.rand(4, 4)
t = torch.cat([t1s, trs])
t

tensor([[1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000],
        [0.6770, 0.8817, 0.2812, 0.1920],
        [0.6807, 0.8855, 0.9864, 0.6339],
        [0.1389, 0.7574, 0.1816, 0.0199],
        [0.8691, 0.1041, 0.0435, 0.0685]])

In [17]:
t = torch.stack([t1s, trs])
t

tensor([[[1.0000, 1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000, 1.0000]],

        [[0.6770, 0.8817, 0.2812, 0.1920],
         [0.6807, 0.8855, 0.9864, 0.6339],
         [0.1389, 0.7574, 0.1816, 0.0199],
         [0.8691, 0.1041, 0.0435, 0.0685]]])

In [19]:
t1 = torch.ones(3, 4)
t2 = torch.rand(3, 4)

print(f"Elementwise multiplication: {t1 * t2}")
print(f"Matrix multiplication: {t1 @ t2.T}")

Elementwise multiplication: tensor([[0.2793, 0.8406, 0.2028, 0.3549],
        [0.4653, 0.4396, 0.3896, 0.2212],
        [0.8718, 0.3839, 0.0749, 0.9687]])
Matrix multiplication: tensor([[1.6776, 1.5158, 2.2993],
        [1.6776, 1.5158, 2.2993],
        [1.6776, 1.5158, 2.2993]])
